services:
  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: fratpos
      MYSQL_USER: fratpos
      MYSQL_PASSWORD: fratpos
      MYSQL_ROOT_PASSWORD: root
