services:
  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306
    command: [ "mysqld", "--sql_mode=" ]
    environment:
      MYSQL_DATABASE: fratpos
      MYSQL_USER: fratpos
      MYSQL_PASSWORD: fratpos
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - 80
    environment:
      PMA_HOST: mysql
