version: '3.3'

services:
  db:
    image: mysql:latest
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: fratpos
      MYSQL_USER: fratpos
      MYSQL_PASSWORD: fratpos

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8881:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: supersecret
