spring:
  application:
    name: fratpos
  datasource:
    url: jdbc:mysql://localhost:3306/fratpos?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: fratpos
    password: fratpos
