package info.kaara.fratpos.security;

public enum Permissions {
	USERS_VIEW,
	USERS_MODIFY,
	NOTIFICATIONS_VIEW,
	NOTIFICATIONS_MODIFY,
	ROLES_VIEW,
	ROLES_MODIFY,
	OBLIGATIONS_VIEW,
	OBLIGATIONS_MODIFY,
	BOOKKEEPING_VIEW,
	BOOKKEEPING_MODIFY,
	REPORTS_VIEW,
	REPORTS_MODIFY,
	POS_VIEW,
	POS_MODIFY,
	PROFILE_VIEW,
	PROFILE_MODIFY
}
